CREATE DATABASE DoAnPhanMem
GO
USE DoAnPhanMem 


CREATE TABLE SanPham
(
  MaSP CHAR(5),
  TenSP NVARCHAR(30),
  HinhSP NVARCHAR(50),
  MoTaSP NVARCHAR(100),
  GiaSP INT,
  SoLuongSP INT,
  MaLoai CHAR(5) NOT NULL,
  MaNSX NVARCHAR(20),
  PRIMARY KEY (MaSP),
CONSTRAINT FK_SanPhamML FOREIGN KEY(MaLoai) REFERENCES LoaiSP(MaLoai)
);

CREATE TABLE LoaiSP
(
  MaLoai CHAR(5),
  TenLoai NVARCHAR(30),
  PRIMARY KEY (MaLoai)
);

CREATE TABLE NhaCungCap
(
	MaNCC CHAR(5), 
	TenNCC NVARCHAR(20),	
	SoDienThoaiNCC VARCHAR(11),
	DiaChi NVARCHAR(20),
  	PRIMARY KEY (MaNCC)
);


CREATE TABLE NhapHang
(
  MaNhapHang CHAR(5),
  MaSP CHAR(5),
  MaNCC CHAR(5),
  NgayNhapSP DATE,
  SoLuongNhap INT,
  PRIMARY KEY (MaNhapHang),
CONSTRAINT FK_NhapHangMaSP FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP),
CONSTRAINT FK_NhapHangMaNCC FOREIGN KEY(MaNCC) REFERENCES NhaCungCap(MaNCC)
);


CREATE TABLE NhanVien
(
  MaUser INT, 
  TenUser VARCHAR(MAX),
  RoleUser VARCHAR(MAX),
  PassWord VARCHAR(MAX),
  PRIMARY KEY (MaUser)
);

CREATE TABLE DonHang
(
  MaDH INT IDENTITY (1, 1) NOT NULL,
  NgayMua DATE,
  MaUser INT,
  TongTien INT
  PRIMARY KEY (MaDH)
CONSTRAINT FK_DonHangMaUser FOREIGN KEY(MaUser) REFERENCES NhanVien(MaUser)
);

CREATE TABLE ChiTietDonHang
(
  MaCTDH INT IDENTITY (1, 1) NOT NULL,
  MaSP CHAR(5),
  MaDH INT,
  SoLuong INT,
  TongTienSP INT,
  PRIMARY KEY (MaCTDH),
CONSTRAINT FK_CTDHMaSP FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP),
CONSTRAINT FK_CTDHMaDH FOREIGN KEY(MaDH) REFERENCES DonHang(MaDH)

);